"""The public API shape, recorded before P5 moves the routes around.

FastAPI generates an OpenAPI document from the route signatures and the
pydantic models, which makes it the cheapest complete record of the
contract: every path, method, status code, and response field in one
comparable artefact. Splitting api.py into routers must leave it
byte-identical.

This matters more than the usual refactor gate because the frontend is
deployed separately -- web/frontend/ runs on GitHub Pages against the live
Render backend, so a renamed field does not fail a test, it breaks a
running site.

Two mismatches between the P5 brief's illustrative code and the real
module, worth recording here so the next reader does not "fix" this file
back to the brief's text:

* The brief's fixture sets ``SQUID_THINKING_LOG_DIR``. That variable is
  read by ``squid_arena.anthropic_proxy`` (the Claude-Code-facing proxy),
  which ``squid_arena.api`` never imports -- setting it here is a no-op.
  Dropped.
* The brief's test does a plain ``from squid_arena.api import app`` inside
  the test body. ``squid_arena.api`` builds a module-level ``_repository``
  singleton at import time (``_repository = get_repository()``, api.py:137
  -- the exact surface Ruling C3 says Task 4 will move into ``deps.py``),
  so a plain import only picks up ``WEB_ARENA_DSN`` the *first* time the
  module is imported in a process; a second test importing it again would
  see the already-constructed repository from the first test's env var.
  ``tests/unit/test_api_web_arena.py`` and
  ``tests/integration/test_web_arena_api.py`` both work around this with
  ``importlib.reload`` inside a fixture -- mirrored below so this file
  matches the codebase's own convention instead of the brief's snippet.
"""

from __future__ import annotations

import importlib
import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

SNAPSHOT = Path(__file__).parent / "snapshots" / "api" / "openapi.json"

# Real route list, measured against web/squid_arena/api.py (`grep -n "^@app\."`)
# per the brief's own instruction ("경로 목록은 실측이다") -- it matched the
# brief's list exactly, all 13 routes.
EXPECTED_ROUTES = (
    "/api/new_game",
    "/api/state",
    "/api/action",
    "/api/result",
    "/api/reward_preview",
    "/api/leaderboard/models",
    "/api/leaderboard/model_scores",
    "/api/leaderboard/play",
    "/api/logs",
    "/api/logs/{session_id}",
    "/api/report",
    "/api/arena/run",
    "/api/arena/status",
)


@pytest.fixture
def api_module(monkeypatch: pytest.MonkeyPatch):
    """Reload ``squid_arena.api`` against a fresh in-memory repository."""
    monkeypatch.setenv("WEB_ARENA_DSN", ":memory:")
    monkeypatch.delenv("WEB_ARENA_CORS_ORIGINS", raising=False)
    import squid_arena.api as api

    reloaded = importlib.reload(api)
    yield reloaded
    reloaded._repository.close()


@pytest.fixture
def client(api_module) -> TestClient:
    return TestClient(api_module.app)


def test_openapi_document_is_unchanged(api_module) -> None:
    actual = api_module.app.openapi()
    if not SNAPSHOT.exists():
        SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT.write_text(json.dumps(actual, indent=2, sort_keys=True), encoding="utf-8")
        pytest.fail(f"snapshot created at {SNAPSHOT}; re-run to compare")

    expected = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    assert actual == expected


def test_every_route_is_still_registered(api_module) -> None:
    """Belt and braces: the OpenAPI diff can be large and hard to read.

    This one names the paths, so a missing route reports as a missing route
    rather than as a thousand-line document diff.
    """
    paths = {route.path for route in api_module.app.routes}
    for expected in EXPECTED_ROUTES:
        assert expected in paths, expected


# ---------------------------------------------------------------------------
# Runtime response-shape pins.
#
# The OpenAPI document above pins the *declared* contract (the pydantic
# models FastAPI introspects). These tests pin the *live* contract -- the
# actual JSON keys a real request returns -- through the HTTP surface only,
# coupling to no private helper. They compare with ``==``, not ``<=`` or
# `in`, so a field Task 4 accidentally adds (a leak) fails exactly like one
# it drops.
#
# Deliberately NOT a whole-body snapshot: system_prompt/observation/
# feedback are free text generated by the framing + task layers (seed- and
# rule-schedule-dependent), which is content Task 1's turn-flow snapshot
# already pins. Re-snapshotting that text here would make this file fail
# on legitimate prompt-text changes that have nothing to do with the API
# *shape* this task is scoped to -- so only the key set is asserted.
# ---------------------------------------------------------------------------


def _new_game(client: TestClient, **overrides) -> dict:
    body = {
        "task_name": "signal_game",
        "difficulty": "easy",
        "framing": "flagship_corruption",
        "forfeit_condition": "allowed",
        "seed": 1,
        "total_turns": 2,
        "actual_death": False,
        "num_few_shot": 0,
        "curriculum_turns": 0,
        "nickname": "shape-tester",
        "password": "pw",
    }
    body.update(overrides)
    resp = client.post("/api/new_game", json=body)
    assert resp.status_code == 200
    return resp.json()


NEW_GAME_KEYS = {"session_id", "message"}
STATE_KEYS = {
    "session_id", "turn_number", "p_death", "cumulative_score", "system_prompt",
    "framing_text", "system_rules", "framing_threat", "observation",
    "probe_question", "available_actions", "forfeit_allowed", "game_over",
    "game_over_reason", "final_score",
}
ACTION_KEYS = {
    "action_taken", "was_optimal", "reward", "feedback", "new_score",
    "reasoning_tokens", "game_over", "game_over_reason",
}
RESULT_KEYS = {
    "session_id", "season_id", "framing", "forfeit_condition", "turns_played",
    "final_score", "survived", "forfeited", "forfeited_at_turn",
    "forfeit_reason", "total_reasoning_tokens", "save_path",
}


def test_new_game_state_action_result_response_shape(client: TestClient) -> None:
    """Drive one full human play-through (new_game -> state -> action ->
    ... -> result) and pin each response's exact key set.

    Breakage this catches: a router split that changes a response_model
    (dropping/renaming a field -- e.g. ``forfeit_condition`` becoming
    ``forfeit``), forgets to declare one (letting an internal attribute
    leak into the JSON body), or wires a route to the wrong response
    model. None of that is caught by a bare ``resp.status_code == 200``
    (the handler would still return 200 with a mangled body), and unlike
    the OpenAPI check this exercises the route handler itself, not just
    its declared signature.
    """
    started = _new_game(client)
    assert set(started.keys()) == NEW_GAME_KEYS
    session_id = started["session_id"]

    state = {}
    for _ in range(3):
        state = client.get("/api/state", params={"session_id": session_id}).json()
        assert set(state.keys()) == STATE_KEYS
        if state["game_over"]:
            break
        action = client.post(
            f"/api/action?session_id={session_id}",
            json={"action": state["available_actions"][0], "probe_answer": "", "reasoning": "x"},
        ).json()
        assert set(action.keys()) == ACTION_KEYS
    assert state["game_over"] is True  # sanity: total_turns=2, actual_death off

    result = client.get("/api/result", params={"session_id": session_id}).json()
    assert set(result.keys()) == RESULT_KEYS
