"""Shared fixtures for integration tests.

Provides a ``StubProvider`` that always returns a parametrisable canned
response, plus helpers for monkey-patching the runner's provider factory
so ``ExperimentRunner.run()`` end-to-end tests stay deterministic and
offline.

Design notes
------------
* ``StubProvider`` implements the full ``LLMProvider`` interface but
  never talks to the network. ``response_fn`` lets individual tests
  control the canned text per call (e.g. alternate stakes).
* The fixtures prefer real ``VanillaAgent`` + real task modules so the
  prompt-assembly / parsing layers are exercised end-to-end.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

import pytest

from squid_game.providers.base import CompletionResult, LLMProvider


# ---------------------------------------------------------------------------
# Stub provider
# ---------------------------------------------------------------------------


@dataclass
class StubProviderCall:
    """Captured provider.complete() invocation."""

    messages: list[dict[str, str]]
    temperature: float
    max_tokens: int


class StubProvider(LLMProvider):
    """Deterministic ``LLMProvider`` replacement for integration tests.

    The provider records every ``complete()`` call in ``calls`` so tests
    can inspect the system/user messages the agent produced. The canned
    response is generated by ``response_fn(call_index, messages)`` which
    defaults to a fixed unified-mode reply (``ACTION: GO`` / ``STAKE: 2``)
    that any task + risk layer can parse.
    """

    def __init__(
        self,
        response_fn: Callable[[int, list[dict[str, str]]], str] | None = None,
        *,
        model: str = "stub-model",
        thinking_tokens: int = 0,
    ) -> None:
        self._model = model
        self._response_fn = response_fn or _default_unified_response
        self._thinking_tokens = thinking_tokens
        self.calls: list[StubProviderCall] = []

    @property
    def model_name(self) -> str:
        return self._model

    def complete(
        self,
        messages: list[dict[str, str]],
        temperature: float = 0.7,
        max_tokens: int = 4096,
    ) -> CompletionResult:
        self.calls.append(
            StubProviderCall(
                messages=[dict(m) for m in messages],
                temperature=temperature,
                max_tokens=max_tokens,
            )
        )
        call_index = len(self.calls) - 1
        text = self._response_fn(call_index, messages)
        return CompletionResult(
            text=text,
            input_tokens=sum(len(m["content"].split()) for m in messages),
            output_tokens=len(text.split()),
            thinking_tokens=self._thinking_tokens,
            finish_reason="stop",
        )


def _default_unified_response(_index: int, _messages: list[dict[str, str]]) -> str:
    """Default canned unified-mode response.

    Includes both an action (``GO``) and a stake (``2``) so Phase-3
    Risk-Choice-Layer cells parse cleanly, while also satisfying the
    legacy ACTION regex.
    """
    return "ACTION: GO\nSTAKE: 2"


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def stub_provider_factory() -> Callable[..., StubProvider]:
    """Return a factory that creates fresh ``StubProvider`` instances.

    Tests inject a custom ``response_fn`` when they need to alternate
    actions per turn (e.g. forfeit scenario).
    """

    def _factory(**kwargs: Any) -> StubProvider:
        return StubProvider(**kwargs)

    return _factory


@pytest.fixture
def patch_runner_provider(monkeypatch: pytest.MonkeyPatch):
    """Patch ``ExperimentRunner._create_provider`` to yield a stub.

    Usage::

        stub = patch_runner_provider()           # default response
        stub = patch_runner_provider(response_fn=my_fn)

    Returns a function that, when called, installs the patch and returns
    the ``StubProvider`` that will be handed out by the factory. The
    same instance is reused for every season in the experiment so tests
    can inspect aggregated calls.
    """
    from squid_game.runner import ExperimentRunner

    def _install(**stub_kwargs: Any) -> StubProvider:
        stub = StubProvider(**stub_kwargs)

        def _fake_create_provider(_provider_config):  # type: ignore[no-untyped-def]
            return stub

        monkeypatch.setattr(
            ExperimentRunner, "_create_provider", staticmethod(_fake_create_provider)
        )
        return stub

    return _install
